Unify posts import

diff --git a/bin/kecs-import b/bin/kecs-import
--- a/bin/kecs-import
+++ b/bin/kecs-import
@@ -13,18 +13,17 @@ users=users
 
 for file in "$@"; do
   # load stmt
-  spec=$(kecs-loadspec comments "$file")
   sql="\
 SET session sql_log_bin=0;
 --
 CREATE TEMPORARY TABLE IF NOT EXISTS raw (
-  id bigint(11) unsigned NOT NULL,
   link bigint(11) unsigned NOT NULL,
-  parent bigint(11) unsigned NOT NULL,
+  id bigint(11) unsigned NOT NULL,
+  parent bigint(11) unsigned NOT NULL DEFAULT 0,
   created int(11) unsigned NOT NULL,
   username char(20) NOT NULL,
   score int(11) NOT NULL,
-  PRIMARY KEY (link, id),
+  PRIMARY KEY (id),
   KEY (username) USING BTREE
 ) DEFAULT CHARSET=utf8mb4;
 --
@@ -32,27 +31,37 @@ LOAD DATA LOCAL INFILE '$file'
 INTO TABLE raw
 FIELDS TERMINATED BY ',' ENCLOSED BY '\"' ESCAPED BY '\"'
 LINES TERMINATED BY '\\n'
-IGNORE 1 LINES
-($spec)
+IGNORE 0 LINES
+(@link,@id,@parent,@created,@username,@score)
 SET
+  link = CONV(@link,36,10),
   id = CONV(@id,36,10),
-  link = CONV(SUBSTRING(@link_id FROM 4),36,10),
-  parent = CONV(SUBSTRING(@parent_id FROM 4),36,10),
-  username = @author,
-  created = @created_utc,
+  parent = CONV(@parent,36,10),
+  created = @created,
+  username = @username,
   score = @score;
+--
+SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
 --
 INSERT INTO users(username)
 SELECT DISTINCT username FROM raw
 ON DUPLICATE KEY UPDATE id=users.id,username=users.username;
 --
 INSERT INTO $tbl(id,link,parent,user,created,score)
-SELECT r.id,r.link,r.parent,u.id,r.created,r.score
+SELECT r.id,r.id,r.parent,u.id,r.created,r.score
 FROM raw AS r
 INNER JOIN $users AS u ON r.username = u.username
 ON DUPLICATE KEY UPDATE id=$tbl.id;
 "
   # import
-  echo "importing comments from $file" >&2
-  mysql "$db" -e "$sql"
+  attempt=1
+  while true; do
+    echo "importing submissions from $file ($attempt)" >&2
+    mysql "$db" -e "$sql" && break
+    sleep 15
+    (( attempt += 1 ))
+    if [ $attempt -gt 3 ]; then
+      echo "error: attempt count exceeded" >&2 && exit 1
+    fi
+  done
 done
